# Generated by Django 5.2.4 on 2025-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours', models.PositiveIntegerField(verbose_name='Horas mínimas')),
                ('max_hours', models.PositiveIntegerField(verbose_name='Horas máximas')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio por hora')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de comisión')),
            ],
            options={
                'verbose_name': 'Regla de precio',
                'verbose_name_plural': 'Reglas de precio',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Estrellas')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_quantity', models.PositiveIntegerField(verbose_name='Cantidad de personas')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('duration', models.PositiveIntegerField(help_text='Duración en horas', verbose_name='Duración en horas')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('ASSIGNED', 'Asignado'), ('ON_ROUTE', 'En camino'), ('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='REQUESTED', max_length=20, verbose_name='Estado')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('payment_proof', models.FileField(upload_to='payment_proofs/', verbose_name='Comprobante de pago')),
                ('refund_proof', models.FileField(blank=True, null=True, upload_to='refund_proofs/', verbose_name='Comprobante de reembolso')),
                ('collaborator_payment_proof', models.FileField(blank=True, null=True, upload_to='collaborator_payments/', verbose_name='Comprobante de pago al colaborador')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
    ]
