# Generated by Django 5.2.4 on 2025-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/', verbose_name='Ícono (PNG)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='Foto 3'),
        ),
    ]
