# Generated by Django 5.2 on 2025-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_clearance', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Certificado policial')),
                ('criminal_clearance', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Certificado penal')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento de antecedentes',
                'verbose_name_plural': 'Documentos de antecedentes',
            },
        ),
    ]
