# Generated by Django 5.2 on 2025-05-31 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación de servicio',
                'verbose_name_plural': 'Asignaciones de servicio',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad requerida')),
                ('date', models.DateField(verbose_name='Fecha del servicio')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Duración (horas)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Solicitud de servicio',
                'verbose_name_plural': 'Solicitudes de servicio',
            },
        ),
    ]
