# Generated by Django 5.2 on 2025-05-31 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.district', verbose_name='Distrito del servicio'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicetype', verbose_name='Tipo de servicio'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest', verbose_name='Solicitud'),
        ),
    ]
